apiVersion: apps/v1
kind: Deployment
metadata:
 name: api
 labels:
  application: incident-logger
  component: backend
spec:
 template:
  metadata:
   name: api
   labels:
    application: incident-logger
    component: backend
  spec:
   containers:
   - name: api
     image: tenyedi96/incident-logger-backend:latest
     ports:
      - containerPort: 8000
        name: backend
 replicas: 1
 selector:
  matchLabels:
   application: incident-logger
   component: backend
