apiVersion: v1
kind: Service
metadata:
 labels:
  application: incident-logger
  component: backend
 name: api
spec:
 type: ClusterIP
 ports:
 - name: api-service
   port: 8000
   targetPort: 8000
 selector:
  application: incident-logger
  component: backend
