apiVersion: v1
kind: Service
metadata:
 labels:
  application: incident-logger
  component: mysql
 name: mysql
spec:
 type: ClusterIP
 ports:
 - name: mysql-service
   port: 3306
   targetPort: 3306
 selector:
  application: incident-logger
  component: mysql
