apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    application: incident-logger
    component: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      application: incident-logger
      component: mysql
  template:
    metadata:
      name: mysql
      labels:
        application: incident-logger
        component: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.4
          ports:
            - containerPort: 3306
              name: mysql
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: example
            - name: MYSQL_DATABASE
              value: incident_db
            - name: MYSQL_USER
              value: appuser
            - name: MYSQL_PASSWORD
              value: appsecret
          volumeMounts:
            - name: mysql-data-vol
              mountPath: /var/lib/mysql
            - name: init-sql
              mountPath: /docker-entrypoint-initdb.d/init.sql
              subPath: init.sql
      volumes:
        - name: mysql-data-vol
          persistentVolumeClaim:
           claimName: mysql-data-pvc
        - name: init-sql
          configMap:
            name: mysql-init
            items:
              - key: init.sql
                path: init.sql
